<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="Resources\strings.en-us.xaml" />
    <Page Remove="Resources\strings.vi-vn.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.11" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.11" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Abstractions" Version="4.3.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\strings.en-us.xaml" />
    <Resource Include="Resources\strings.vi-vn.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SettingsColor.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>SettingsColor.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="SettingsColor.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>SettingsColor.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
