//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenWinOffice {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.9.0.0")]
    internal sealed partial class SettingsColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsColor defaultInstance = ((SettingsColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsColor())));
        
        public static SettingsColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SystemDefault")]
        public string ThemeMode {
            get {
                return ((string)(this["ThemeMode"]));
            }
            set {
                this["ThemeMode"] = value;
            }
        }
    }
}
